### PR TITLE
 [Feature] All InstagramShareTypes implemented in InstagramDirectShareRequest

### PR DESCRIPTION
**Pull request by DanielePancottini**
Completely reviewed InstagramDirectShareRequest class with following changes:

- Added and handled all ShareTypes provided by instagram API
- Changed entity builder logic with MultipartEntityBuilder
- Minor adjustments

### CODE REVIEW

**Comment by jemand771** [comment]
That's what i tried to do with #285 but I kinda forgot about it. 
Awesome, thank you!

Are we able to get, approve and decline pending direct requests yet? Implemented that over there. I'll clean things up on my side and re-open that one.

**Comment by DanielePancottini** [comment]
@jemand771 You're welcome!! 😄 

At the moment we can't handle pending direct requests, if you want I can try to do some code 👍

**Comment by jemand771** [comment]
No need to do so, I've already got that part ready 😄

**Comment by GehadG** [comment]
@DanielePancottini Hey !
That's really a great addition ! i was wondering if you tested it recently ?
because i tried it and its giving me this : 
`Direct-share request result: 403, {"message": "Client upgrade needed.", "status": "fail"}`

**Comment by DanielePancottini** [comment]
Hi,

this addition was finished in June, so it is possibile that somethings on
Instagram API is changed.

Post your code, I will found the issue

Il ven 11 ott 2019, 02:02 Gehad Gamal <notifications@github.com> ha scritto:

**Comment by GehadG** [comment]
Thanks for the fast response , i have downloaded the last version , then applied your changes in it `instagram.sendRequest(InstagramDirectShareRequest.builder(InstagramDirectShareRequest.ShareType.PHOTO).recipients(recepients).threadId(thread.thread_id).photoFilePath("selfie-bad-skin.jpg").build());`

**Comment by GehadG** [comment]
@DanielePancottini i have also tried with recipients only and threadId only , same thing

**Comment by GehadG** [comment]
@DanielePancottini any updates regarding this ^^

**Comment by DanielePancottini** [comment]
Hi @GehadG, I haven't got much time to check the issue, probably I will check this problem tomorrow. 

Just to remove some causes, what version of instagram4j are you using?

**Comment by GehadG** [comment]
@DanielePancottini i used the latest release
also i used the latest development version ( updated 2 days ago )

**Comment by DanielePancottini** [comment]
@GehadG the problem seems to be the client version into `InstagramConstants.class`.
This class wasn't recently maintained and so some constants need to be upgrated.

The code will work setting the field `DEVICE_ANDROID_VERSION` into `InstagramConstants.class` equals than `28 `or `29`.

**Comment by GehadG** [comment]
@DanielePancottini i tried setting it to 28 and 29 
Still same thing unfortunately

**Comment by GehadG** [comment]
@DanielePancottini Have you tested it already and it works ?
Because i am thinking about trying to give it a go my self to implemented and create a PR , however if it worked on your side then it would be pointless to do that^^

**Comment by DanielePancottini** [comment]
@GehadG recently there was a PR that upgraded some constants including device properties. Maybe, into the next version of this API the problem will solve.

**Comment by jvogit** [comment]
Addressed in rewrite or no longer relevant.

**Pull request closed without merging**
