### PR TITLE
Added User-Presence / Online-Status

### PR DESCRIPTION
**Pull request by GiorgosXou**
**About** [Added User-Presence / Online-Status] More Info At #370

### CODE REVIEW

**Comment by GiorgosXou** [comment]
Tests&More-Infos probably coming soon on comments [...]

**Comment by GiorgosXou** [comment]
# Important
⚠️ **Updates are a Fast forward implementation**
⚠️ **Updates are not Fully Tested yet** 
⚠️ **I am not a profesional programmer yet** 
⚠️ **I am new to java** 

💛 **Thanks you for understanding**

# Updated Files

> InstagramItem.java 

-  filter_type
-  image_versions2
-  
-  
-  
-  
-  
-  
-  
> StoryPollItem.java

# Added Files

**Comment by jvogit** [comment]
@GiorgosXou 
Hello! I think majority of changes to Stories here have been addressed by #352

**Comment by GiorgosXou** [comment]
@jvogit 
Hello! 

```java
InstagramGetUserReelMediaFeedRequest request = new InstagramGetUserReelMediaFeedRequest(292864121);
InstagramGetUserReelMediaFeedResult result = instagram.sendRequest(request);
```
am i wrong or the request returns  `InstagramtUserReelMediaFeedResult` instead of `InstagramGetUserReelMediaFeedResult` ?

**Comment by jvogit** [comment]
> @jvogit
> Hello!
> 
> From `InstagramGetUserReelMediaFeedRequest.java`:
> 
> ```java
> ...
>     public InstagramUserReelMediaFeedResult parseResult(int resultCode, String content) {
>         return parseJson(resultCode, content, InstagramUserReelMediaFeedResult.class);
>     }
> ```
> 
> From #352:
> 
> ```java
> ...
> InstagramGetUserReelMediaFeedRequest request = new InstagramGetUserReelMediaFeedRequest(292864121);
> InstagramGetUserReelMediaFeedResult result = instagram.sendRequest(request);
> ```
> 
> am i wrong or the request returns `InstagramtUserReelMediaFeedResult` instead of `InstagramGetUserReelMediaFeedResult` ?
> 
> Also forgive me but i am kind of confused, because i haven't found any way to get most of the things that i've added in `InstagramItem.java` class with any other way [...]

It returns InstagramUserReelMediaResult . It was outdated example that I'll update now!

What things specifically you need in InstagramItem?

**Comment by GiorgosXou** [comment]
the **issue** seems to be with `InstagramGetUserReelMediaFeedRequest.java` and not with your example because `InstagramtUserReelMediaFeedResult` has nothing compared to `InstagramtUserReelMediaFeedResult`

**Comment by jvogit** [comment]
> the **issue** seems to be with `InstagramGetUserReelMediaFeedRequest.java` and not with your example because `InstagramtUserReelMediaFeedResult` has nothing compared to `InstagramGetUserReelMediaFeedResult `
> 
> _(except now that i've added pretty much everything into `InstagramtUserReelMediaFeedResult` [...])_
> 
> > What things specifically you need in InstagramItem?
> 
> story_polls , story_sliders, story_questions, story_poll_voter_infos, story_slider_voter_infos, story_question_responder_infos , etc. whitch i've added in `InstagramtUserReelMediaFeedResult`

InstagramUserReelMediaFeedResult is returned. It was changed from InstagramGetUserReelMediaFeedResult .

The changes are present in [InstagramStoryItem ](https://github.com/brunocvcunha/instagram4j/pull/352/commits/09fce08295d84921d6269881f4f695df238ef718#diff-a2013c788a26f6231e50c318d4055a4b)

**Comment by GiorgosXou** [comment]
i am so confused, so your request wasn't aprroved yet so it wasn't in the main-master branch?

**Comment by GiorgosXou** [comment]
Omg i did all  this work and now i see that it was just this `InstagramUserReelMediaFeedResult`

**Comment by GiorgosXou** [comment]
Nop , i am again confused, anyways , thanks

**Comment by GiorgosXou** [comment]
@jvogit 
I am really sory but just a **Last question,** what do i have to do to get the changes you have made? (because if i am right they are not merged yet)

**Comment by jvogit** [comment]
> @jvogit
> I am really sorry but just a **Last question,** what do i have to do to get the changes you have made? (because if i am right they are not merged yet)
> 
> Do i have to manually download and copy paste them or is there any faster way?
> 
> _(i am going AFK, to sleep)_

I believe you can git fetch (my branch for stories) then merge them into your repository if you want the changes. You should do this in another separate branch.

**Comment by jvogit** [comment]
Addressed in rewrite or no longer relevant.

**Pull request closed without merging**
